<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Miscellaneous language phrases


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'block_ip_button' => 'Блокувати IP',
	'browse_categories' => 'Огляд категорій',
	'captcha_approve_fix' => "Щоб уникнути перевірки в майбутньому, будь ласка підтвердіть свій аккаунт.",
	'captcha_confirm_fix' => 'Щоб уникнути перевірки в майбутньому, будь ласка ^5підтвердіть адресу електронної пошти^6.',
	'captcha_error' => 'Будь ласка, пройдіть анти-спам перевірку',
	'captcha_label' => 'Анти-спам перевірка:',
	'captcha_login_fix' => 'Щоб уникнути перевірки в майбутньому, будь ласка ^1увійдіть^2 або ^3зареєструйтесь^4.',
	'feed_a_edited_prefix' => 'Відповідь відредаговано: ',
	'feed_a_prefix' => 'Відповіді: ',
	'feed_a_reshown_prefix' => 'Заново показана відповідь: ',
	'feed_a_selected_prefix' => 'Відповідь обрана: ',
	'feed_c_edited_prefix' => 'Коментар відредаговано: ',
	'feed_c_moved_prefix' => 'Коментар переміщено: ',
	'feed_c_prefix' => 'Прокоментовано: ',
	'feed_c_reshown_prefix' => 'Заново показаний коментар: ',
	'feed_closed_prefix' => 'Закрито: ',
	'feed_edited_prefix' => 'Відредаговано: ',
	'feed_hidden_prefix' => 'Приховано: ',
	'feed_not_found' => 'Feed не знайдено',
	'feed_recategorized_prefix' => 'Змінена категорія: ',
	'feed_reopened_prefix' => 'Заново відкритий: ',
	'feed_reshown_prefix' => 'Заново показаний: ',
	'feed_retagged_prefix' => 'Змінені теги: ',
	'feedback_email' => 'Адреса Вашої електронної пошти: (не обов\'язково)',
	'feedback_empty' => 'Використовуйте це поле для відправлення коментарів та пропозицій',
	'feedback_message' => 'Ваші коментарі або пропозиції для ^:',
	'feedback_name' => 'Ваше ім\'я: (не обов\'язково)',
	'feedback_sent' => 'Ваше повідомлення було надіслано. Дякую.',
	'feedback_title' => 'Зворотній зв\'язок',
	'form_security_again' => "Будь ласка, натисніть ще раз для підтвердження",
	'form_security_reload' => "Будь ласка, перезавантажте сторінку і спробуйте знову",
	'hide_all_ip_button' => 'Приховати всі повідомлення з цієї IP',
	'host_name' => 'Хост:',
	'inbox' => "Вхідні",
	'matches_blocked_ips' => 'Список заблокованих IP:',
	'message_empty' => 'Пожалуйста, введите сообщение, чтобы отправить этому пользователю',
	'message_explanation' => 'Сповіщення буде відправлено від ^. Вашу адресу електронної пошти не буде показано, якщо Ви не будете включати її в повідомлення.',
	'message_for_x' => 'Повідомлення для ^:',
	'message_limit' => 'Щось Ви зачастили надсилати повідомлення - спробуйте продовжити через годину',
	'message_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4, щоб надіслати особисте повідомлення.',
	'message_recent_history' => 'Історія повідомлень з ^',
	'message_sent' => 'Ваше повідомлення надіслано',
	'more_favorite_qs' => "Більше обраних питань...",
	'more_favorite_tags' => "Більше обраних тегів...",
	'more_favorite_users' => "Більше обраних користувачів...",
	'my_favorites_title' => 'Моє обране',
	'nav_all_my_updates' => 'Всі оновлення',
	'nav_my_content' => 'Мій вміст',
	'nav_my_details' => 'Мої дані',
	'nav_my_favorites' => 'Моє обране',
	'nav_user_activity' => "Остання активність",
	'nav_user_as' => "Всі відповіді",
	'nav_user_pms' => "Особисті повідомлення",
	'nav_user_qs' => "Всі питання",
	'nav_user_wall' => "Стіна",
	'next_step' => 'Далі',
	'no_activity_from_x' => 'Не активний: ^',
	'no_favorite_categories' => 'Немає обраних категорій',
	'no_favorite_qs' => 'Немає обраних питань',
	'no_favorite_tags' => 'Немає обраних тегів',
	'no_favorite_users' => 'Немає обраних користувачів',
	'no_recent_updates' => 'Немає останніх оновлень',
	'no_updates_content' => 'Немає останніх оновлень мого вмісту',
	'no_updates_favorites' => 'Немає останніх оновлень мого обраного',
	'outbox' => "Надіслані",
	'pm_inbox_title' => "Отримано повідомлення",
	'pm_outbox_title' => "Повідомлення надіслано",
	'private_message_title' => 'Надіслати особисте повідомлення',
	'recent_activity_from_x' => 'Остання активність: ^',
	'recent_updates_content' => 'Останні оновлення мого вмісту',
	'recent_updates_favorites' => 'Останні оновлення мого обраного',
	'recent_updates_title' => 'Останні оновлення для мене',
	'site_in_maintenance' => 'Технічне обслуговування сайту - будь ласка, зайдіть пізніше.',
	'suggest_favorites_add' => 'Для додавання питання або будь-якого іншого елемента в обране, натисніть ^ зверху сторінки.',
	'suggest_update_favorites' => 'Щоб отримувати більше оновлень, додайте в ^1обране^2.',
	'unblock_ip_button' => 'Розблокувати IP',
	'your_a_commented' => "Ваша відповідь прокоментована",
	'your_a_edited' => "Ваша відповідь відредагована",
	'your_a_hidden' => "Ваша відповідь прихована",
	'your_a_questioned' => "Запитали від Вашої відповіді",
	'your_a_reshown' => "Ваша відповідь знову відображена",
	'your_a_selected' => "Вашу відповідь обрано найкращою",
	'your_c_edited' => "Ваш коментар відредаговано",
	'your_c_followed' => "Після Вашого коментаря додали ще один",
	'your_c_hidden' => "Ваш коментар приховано",
	'your_c_moved' => "Ваш коментар переміщено",
	'your_c_reshown' => "Ваш коментар знову відображено",
	'your_q_answered' => "На Ваше запитання відповіли",
	'your_q_closed' => "Ваше питання закрито",
	'your_q_commented' => "Ваше запитання прокоментовано",
	'your_q_edited' => "Ваше запитання відредаговано",
	'your_q_hidden' => "Ваше запитання приховано",
	'your_q_recategorized' => "Вашому запитанню змінили категорію",
	'your_q_reopened' => "Ваше питання знову відкрито",
	'your_q_reshown' => "Ваше запитання знову відображено",
	'your_q_retagged' => "У Вашого запитання змінились теги",
);