<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'_decimal_point' => '.',
	'_thousands_separator' => ',',
	'_thousands_suffix' => ' тис.',
	'_millions_suffix' => ' млн.',
	'1_answer' => '1 відповідь',
	'1_comment' => '1 коментар',
	'1_day' => '1 дн.',
	'1_disliked' => '1 ПРОТИ',
	'1_flag' => '1 відмітив',
	'1_hour' => '1 г',
	'1_liked' => '1 ЗА',
	'1_minute' => '1 хв',
	'1_month' => '1 міс.',
	'1_point' => '1 очко',
	'1_question' => '1 питання',
	'1_second' => '1 сек',
	'1_tag' => '1 тег',
	'1_user' => '1 користувач',
	'1_view' => '1 перегляд',
	'1_vote' => '1 голос',
	'1_week' => '1 тижд.',
	'1_year' => '1 р.',
	'add_category_x_favorites' => 'Додати категорію ^ в моє обране',
	'add_favorites' => 'Додати в моє обране',
	'add_tag_x_favorites' => 'Додати тег ^ в моє обране',
	'all_categories' => 'Всі категорії',
	'anonymous' => 'Анонім',
	'answer_edited' => 'відповідь відредаговано',
	'answer_reshown' => 'відповідь показано наново',
	'answer_selected' => 'відповідь обрана',
	'answered_qs_in_x' => 'Більшість відповідей в ^',
	'answered_qs_title' => 'Найбільше число відповідей',
	'answered' => 'відповів',
	'asked_related_q' => 'задав пов\'язане питання',
	'asked' => 'запитав',
	'by_x' => 'від ^',
	'cancel_button' => 'Відміна',
	'closed' => 'закрито',
	'comment_edited' => 'редагувати коментар',
	'comment_moved' => 'перемістити коментар',
	'comment_reshown' => 'показати коментар',
	'commented' => 'залишив коментар',
	'date_day_min_digits' => 2, // 1 або 2
	'date_format_other_years' => '^day ^month, ^year',
	'date_format_this_year' => '^day ^month',
	'date_month_1' => 'Січ',
	'date_month_2' => 'Лют',
	'date_month_3' => 'Бер',
	'date_month_4' => 'Кві',
	'date_month_5' => 'Тра',
	'date_month_6' => 'Чер',
	'date_month_7' => 'Лип',
	'date_month_8' => 'Сер',
	'date_month_9' => 'Вер',
	'date_month_10' => 'Жов',
	'date_month_11' => 'Лис',
	'date_month_12' => 'Гру',
	'date_year_digits' => 2, // 2 або 4
	'edited' => 'редагувати',
	'email_error' => "Виникла помилка при спробі відправити email.",
	'field_required' => 'Будь ласка, введіть що-небудь в це поле.',
	'file_upload_limit_exceeded' => "Розмір файлу перевищує встановлений сервером ліміт",
	'general_error' => 'Помилка сервера - спробуйте ще раз',
	'hidden' => 'прихований',
	'highest_users' => 'Рейтинг найкращих користувачів',
	'hot_qs_in_x' => 'Гарячі питання в ^',
	'hot_qs_title' => 'Гаряче',
	'image_not_read' => 'Зображення неможливо відкрити. Завантажте ще раз: ^',
	'image_too_big_x_pc' => 'Занадто велике зображення. Змініть масштаб на ^% та спробуйте знову.',
	'in_category_x' => 'в категорії ^',
	'ip_address_x' => 'IP адреса ^',
	'logged_in_x' => 'Привіт, ^',
	'max_length_x' => 'Максимальна довжина - ^ символів',
	'max_upload_size_x' => "Макс. розмір завантажуванного файлу: ^",
	'me' => 'мене',
	'meta_order' => '^what^when^who^where', // Ви можете змінити порядок виведення, але не перекладати! Наприклад: <відповів> <15 годин тому> <Адмін (500 балів)> <в категорії Основні питання>
	'min_length_x' => 'Будь ласка, додайте більше інформації (мінімум ^ символів)',
	'moved' => 'переміщено',
	'nav_activity' => 'Вся Активність',
	'nav_admin' => 'Адмін-панель',
	'nav_ask' => 'Задати питання',
	'nav_categories' => 'Категорії',
	'nav_feedback' => 'Зворотній зв\'язок',
	'nav_home' => 'Головна',
	'nav_hot' => 'Гаряче!',
	'nav_login' => 'Вхід',
	'nav_logout' => 'Вихід',
	'nav_most_answers' => '> відповідей',
	'nav_most_recent' => 'Останні',
	'nav_most_views' => '> переглядів',
	'nav_most_votes' => '> голосів',
	'nav_no_answer' => 'Без відповіді',
	'nav_no_selected_answer' => 'Без найкращої відповіді',
	'nav_no_upvoted_answer' => 'Без голосів за відповідь',
	'nav_qa' => 'В&О',
	'nav_qs' => 'Питання',
	'nav_register' => 'Реєстрація',
	'nav_tags' => 'Теги',
	'nav_unanswered' => 'Без відповідей',
	'nav_updates' => 'Мої оновлення',
	'nav_users' => 'Користувачі',
	'newest_users' => 'Нові користувачі',
	'no_active_users' => 'Активних користувачів не знайдено',
	'no_answers_found' => 'Відповідей не знайдено',
	'no_answers_in_x' => 'Без відповідей в ^',
	'no_categories_found' => 'Категорії не знайдені',
	'no_category' => 'Немає категорії',
	'no_comments_found' => 'Коментарів не знайдено',
	'no_comments_in_x' => 'Немає коментарів в ^',
	'no_questions_found' => 'Питань не знайдено',
	'no_questions_in_x' => 'Немає питань в ^',
	'no_related_qs_title' => 'Пов\'язаних запитань не знайдено',
	'no_results_for_x' => 'Для ^ результатів немає',
	'no_tags_found' => 'Теги не знайдені',
	'no_una_questions_found' => 'Питань без відповідей не знайдено',
	'no_una_questions_in_x' => 'Немає питань без відповідей в ^',
	'no_unselected_qs_found' => 'Немає питань без найкращої відповіді',
	'no_unupvoteda_qs_found' => 'Немає питань без голосів за відповіді',
	'page_label' => 'Сторінка:',
	'page_next' => 'туди',
	'page_not_found' => 'Сторінка не знайдена',
	'page_prev' => 'сюди',
	'popular_tags' => 'Популярні теги',
	'questions_tagged_x' => 'Запитання з тегом ^',
	'recategorized' => 'категорія змінена',
	'recent_activity_in_x' => 'Остання активність в ^',
	'recent_activity_title' => 'Остання активність',
	'recent_as_in_x' => 'Останні питання з відповідями в ^',
	'recent_as_title' => 'Останні питання з відповідями',
	'recent_cs_in_x' => 'Останні додані коментарі в ^',
	'recent_cs_title' => 'Останні додані коментарі',
	'recent_qs_as_in_x' => 'Останні питання і відповіді в ^',
	'recent_qs_as_title' => 'Останні питання і відповіді',
	'recent_qs_in_x' => 'Останні питання в ^',
	'recent_qs_title' => 'Останні питання',
	'related_qs_title' => 'Схожі питання',
	'remove_favorites' => 'Видалити з мого обраного',
	'remove_x_favorites' => 'Видалити ^ з мого обраного',
	'reopened' => 'відкритий',
	'reshown' => 'показаний',
	'results_for_x' => 'Результати пошуку для ^',
	'retagged' => 'теги змінені',
	'save_button' => 'Зберегти зміни',
	'search_button' => 'Знайти',
	'search_explanation' => 'Будь ласка, введіть текст в поле пошуку та спробуйте ще раз',
	'search_title' => 'Результати пошуку',
	'selected' => 'обраний',
	'send_button' => 'Відправити',
	'since_x' => 'зареєструвався ^',
	'suggest_ask' => 'Ви можете почати, ^1задавши питання^2.',
	'suggest_category_qs' => 'Для отримання більш повної інформації подивіться ^1всі питання в цій категорії^2.',
	'suggest_qs_tags' => 'Для отримання більш повної інформації подивіться в ^1списку питань^2 або у ^3популярних тегах^4.',
	'suggest_qs' => 'Для отримання більш повної інформації подивіться ^1список питань^2.',
	'to_x' => "в ^",
	'unanswered_qs_in_x' => 'Питання без відповідей в ^',
	'unanswered_qs_title' => 'Останні питання без відповідей',
	'unselected_qs_in_x' => 'Питання без найкращої відповіді в ^',
	'unselected_qs_title' => 'Останні питання без найкращої відповіді',
	'unupvoteda_qs_in_x' => 'Питання без голосів за відповіді в ^',
	'unupvoteda_qs_title' => 'Останні запити без голосів за відповіді',
	'upload_limit' => 'Занадто багато завантажень - спробуйте пізніше',
	'view_q_must_be_approved' => 'Ваш обліковий запис повинен бути схвалений для перегляду сторінок питань. Будь ласка, зачекайте або ^1додайте більше інформації^2.',
	'view_q_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електроної пошти^6 для перегляду питання.',
	'view_q_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3ареєструйтесь^4 щоб подивитися питання.',
	'viewed_qs_in_x' => 'Питання з найбільшими переглядами у ^',
	'viewed_qs_title' => 'Питання з найбільшими переглядами',
	'vote_disabled_approve' => "Щоб проголосувати ЗА підтвердіть свій аккаунт",
	'vote_disabled_down' => 'Голосування проти доступне тільки деяким користувачам',
	'vote_disabled_down_approve' => "Щоб проголосувати ПРОТИ підтвердіть свій аккаунт",
	'vote_disabled_hidden_post' => 'Ви не можете голосувати за приховані повідомлення',
	'vote_disabled_hidden_a' => 'Ви не можете голосувати за приховані відповіді',
	'vote_disabled_hidden_q' => 'Ви не можете голосувати за приховані питання',
	'vote_disabled_level' => 'Голосування доступне тільки деяким користувачам',
	'vote_disabled_my_post' => 'Ви не можете голосувати за свої повідомлення',
	'vote_disabled_my_a' => 'Ви не можете голосувати за свої відповіді',
	'vote_disabled_my_q' => 'Ви не можете голосувати за свої питання',
	'vote_disabled_q_page_only' => 'Будь ласка, передивіться це питання, щоб проголосувати',
	'vote_disabled_queued' => 'Ви можете голосувати тільки за схвалені повідомлення',
	'vote_down_must_confirm' => 'Для голосування ПРОТИ ^5підтвердіть адресу своєї електроної пошти^6.',
	'vote_down_popup' => 'Натисніть, щоб проголосувати проти',
	'vote_limit' => 'Ви занадто часто голосуєте - спробуйте пізніше',
	'vote_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електроної пошти^6 щоб проголосувати.',
	'vote_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4, щоб проголосувати.',
	'vote_not_allowed' => 'Голосувати за це не можна',
	'vote_up_popup' => 'Натисніть, щоб проголосувати ЗА',
	'voted_down_popup' => 'Ви голосували ПРОТИ - натисніть, щоб скасувати голос',
	'voted_qs_in_x' => 'Більшість голосів за питання в ^',
	'voted_qs_title' => 'Більшість голосів за питання',
	'voted_up_popup' => 'Ви голосували ЗА - натисніть, щоб скасувати голос',
	'written' => '', // blank in English - placeholder for other languages
	'x_ago' => '^ назад',
	'x_answers' => '^ відповідей',
	'x_comments' => '^ коментарів',
	'x_days' => '^ днів',
	'x_disliked' => '^ не цікавить',
	'x_flags' => '^ відміток',
	'x_hours' => '^ г',
	'x_liked' => '^ цікавить',
	'x_minutes' => '^ хв',
	'x_months' => '^ міс.',
	'x_points' => '^ балів',
	'x_questions' => '^ питань',
	'x_seconds' => '^ сек',
	'x_tags' => '^ тегів',
	'x_users' => '^ користувачів',
	'x_views' => '^ переглядів',
	'x_votes' => '^ голосів',
	'x_weeks' => '^ тижн.',
	'x_years' => '^ р.',
);
