<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'confirm_button' => 'Підтвердіть адресу електронної пошти',
	'email_code_another' => "надіслати знову",
	'email_code_emailed' => "Код підтвердження надіслано на Вашу електронну пошту",
	'email_code_label' => 'Код:',
	'email_code_wrong' => 'Неправильний код',
	'handle_blocked' => "Заборонене ім\'я користувача - спробуйте інше",
	'about' => 'Про сайт',
	'add_user_x_favorites' => 'Додати користувача ^ в моє обране',
	'approve_required' => 'Будь ласка, трохи зачекайте, поки Ваш аккаунт підтвердять. Перейти у ^1свій профіль^2.',
	'approve_title' => "Користувач очікує підтвердження",
	'approve_user_button' => "Підтвердити користувача",
	'approved_user' => "Підтверджений користувач",
	'avatar_default' => 'За замовчуванням',
	'avatar_gravatar' => 'Показувати мій ^1Gravatar^2',
	'avatar_label' => 'Аватар:',
	'avatar_none' => 'Без аватара',
	'block_user_button' => 'Блокування користувача',
	'blocked_users' => 'Заблоковані користувачі',
	'category_level_add' => " - ^1додати тип кожної категорії^2",
	'category_level_in' => "в наступних категоріях:",
	'category_level_label' => "Тип кожної категорії:",
	'category_level_none' => "Оновлень немає",
	'change_email_link' => ' - ^1змінити email^2',
	'change_password' => 'Зміна паролю',
	'confirm_complete' => 'Адресу Вашої електронної пошти підтверджено.',
	'confirm_emailed' => 'Посилання для підтвердження було відправлено на Вашу електронну пошту. Будь ласка, натисніть на посилання, щоб підтвердити свою адресу електронної пошти.',
	'confirm_required' => 'Для завершення реєстрації, будь ласка перейдіть за посиланням з листа, надісланого Вам по електронній пошті, або ^1запитайте лист заново^2.',
	'confirm_title' => 'Підтвердження електронної пошти',
	'confirm_wrong_log_in' => 'Невірний код - будь ласка, ^1увійдіть^2 для відправки нового посилання',
	'confirm_wrong_resend' => 'Невірний код - натисніть нижче, щоб відправити нове посилання',
	'delete_user_button' => 'Видалити користувача',
	'edit_profile' => "Редагувати мій профіль",
	'edit_user_button' => 'Редагувати користувача',
	'email_confirmed' => 'Підтверджено.',
	'email_exists' => 'Ця адреса електронної пошти вже використовується',
	'email_handle_label' => 'Ім\'я користувача або адресу електронної пошти:',
	'email_invalid' => 'Електронна пошта невірна - уважно перевірте введені дані',
	'email_label' => 'Електронна пошта:',
	'email_not_confirmed' => 'Не підтверджено',
	'email_please_confirm' => 'Будь ласка, ^5підтвердіть^6',
	'email_required' => 'Введіть адресу електронної пошти',
	'forgot_link' => 'Я забув свій пароль',
	'full_name' => 'Повне ім\'я',
	'handle_empty' => 'Ім\'я користувача не повинно бути пустим',
	'handle_exists' => 'Ім\'я користувача зайнято - будь ласка, спробуйте інше',
	'handle_has_bad' => 'Ім\'я користувача не повинно містити: ^',
	'handle_label' => 'Ім\'я користувача:',
	'hide_all_user_button' => 'Приховати всі повідомлення цього користувача',
	'last_login_label' => 'Останній вхід:',
	'last_write_label' => 'Останні дії:',
	'level_admin' => 'Адміністратор',
	'level_editor' => 'Редактор',
	'level_expert' => 'Експерт',
	'level_for_category' => "^1 для ^2",
	'level_in_general' => "в загальній",
	'level_moderator' => 'Модератор',
	'level_super' => 'Супер-адміністратор',
	'location' => 'Місцезнаходження',
	'log_in_to_access' => 'Ви можете ^1увійти^2 для доступу в аккаунт.',
	'login_button' => 'Увійти',
	'login_limit' => 'Занадто багато спроб входу - спробуйте через годину',
	'login_title' => 'Вхід',
	'mass_mailings_explanation' => 'Підписатися на розсилку',
	'mass_mailings' => 'Масові розсилки:',
	'member_for' => 'Стаж на сайті:',
	'member_type' => 'Група:',
	'new_password_1' => 'Новий пароль:',
	'new_password_2' => 'Повторіть новий пароль:',
	'no_blocked_users' => 'Заблоковані користувачі не знайдені',
	'no_permission' => 'У Вас немає прав для виконання цієї операції',
	'old_password' => 'Старий пароль:',
	'only_shown_admins' => '(бачать тільки адміністратори)',
	'only_shown_editors' => "(бачать тільки редактори та вище)",
	'only_shown_experts' => "(бачать тільки експерти та вище)",
	'only_shown_moderators' => '(бачать тільки модератори та вище)',
	'password_changed' => 'Пароль змінено',
	'password_label' => 'Пароль:',
	'password_min' => 'Пароль повинен бути не менше ^ символів',
	'password_mismatch' => 'Нові паролі не співпадають',
	'password_none' => 'Немає. Щоб безпосередньо увійти, встановіть пароль нижче.',
	'password_sent' => 'Ваш новий пароль було відправлено по електронній пошті',
	'password_to_set' => 'Встановіть на сторінці свого аккаунта',
	'password_wrong' => 'Пароль не вірний',
	'private_messages_explanation' => 'Дозволити користувачам надсилати мені електронні листи (адреса не відображається)',
	'private_messages' => 'Особисті повідомлення:',
	'profile_saved' => 'Профіль збережено',
	'register_button' => 'Реєстрація',
	'register_limit' => 'Занадто багато реєстрацій - спробуйте через годину',
	'register_suspended' => 'Реєстрація нових користувачів тимчасово призупинено. Будь ласка, спробуйте пізніше.',
	'register_title' => 'Реєстрація нового користувача',
	'registered_label' => "Зареєстрований:",
	'registered_user' => 'Зареєстрований користувач',
	'remember' => "Запам'ятати",
	'remember_label' => 'Запам\'ятати мене на цьому комп\'ютері',
	'remove_avatar' => 'Прибрати аватар:',
	'reset_title' => 'Скидання забутого паролю',
	'save_profile' => 'Зберегти профіль',
	'save_user' => 'Зберегти користувача',
	'send_confirm_button' => 'Надіслати посилання для підтвердження',
	'send_reset_button' => 'Надіслати скидання паролю на пошту',
	'send_reset_note' => 'Повідомлення буде надіслано на Вашу електронну адресу з інструкціями.',
	'special_users' => 'Спеціальні користувачі',
	'terms_not_accepted' => "Ви повинні прийняти правила.",
	'unblock_user_button' => 'Розблокуваати користувача',
	'unsubscribe_complete' => 'Ви відписалися від масової розсилки. Надіслано ^0. Ви можете підписатися заново в будь-який час зі сторінки свого ^1аккаунта^2.', 
	'unsubscribe_title' => 'Відписатися від розсилки',
	'unsubscribe_wrong_log_in' => 'Невірний код - будь ласка, ^1увійдіть^2, щоб відписатися',
	'unsubscribe' => 'Відписатися:',
	'user_blocked' => '(заблокований)',
	'user_not_found' => 'Користувач не знайдений',
	'wall_posts' => "Стіна повідомлень:",
	'wall_posts_explanation' => "Дозволити користувачам розміщати повідомлення на Вашій стіні (Вам буде надіслано сповіщення на електронну пошту)",
	'website' => 'Сайт',
	'x_ago_from_y' => '^1 тому від ^2',
);
