<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'1_answer_title' => '1 Відповідь',
	'a_convert_to_c_on' => 'Конвертувати відповідь у коментар на:',
	'a_convert_to_c' => 'Конвертувати відповідь у коментар',
	'a_convert_warn_cs' => 'Увага: конвертування безповоротно та коментарі у відповіді/ях перемістяться.',
	'a_convert_warn' => 'Увага: конвертування безповоротно.',
	'a_notify_email' => 'Відправити мені лист на цю адресу, якщо моя відповідь обрана або прокоментована:',
	'a_notify_label' => 'Відправити мені лист, якщо моя відповідь обрана або прокоментована',
	'a_notify_x_label' => 'Відправити меня лист (^) якщо моя відповідь обрана або прокоментована',
	'a_waiting_your_approval' => 'Відповідь очікує Вашого схвалення',
	'a_your_waiting_approval' => 'Ваша відповідь скоро буде перевірена і схвалена.',
	'add_answer_button' => 'Відповісти',
	'add_comment_button' => 'Прокоментувати',
	'add_q_favorites' => 'Додати це питання в моє обране',
	'anon_name_label' => "Відображуване ім\'я (за бажанням):",
	'answer_button' => 'відповісти',
	'answer_limit' => 'Дуже часто відповідаєте - спробуйте ще раз пізніше',
	'answer_must_be_approved' => 'Ваш обліковий запис поки що не схвалений, будь ласка, трохи зачекайте. Перейти в ^1свій профіль^2.',
	'answer_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електронної пошти^6 щоб відповісти на це питання.',
	'answer_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4 щоб відповісти на це питання.',
	'answer_q_popup' => 'Відповідь на питання',
	'approve_button' => 'схвалити',
	'approve_a_popup' => 'Схвалити відповідь',
	'approve_c_popup' => 'Схвалити коментар',
	'approve_q_popup' => 'Схвалити питання',
	'ask_button' => 'Задати питання',
	'ask_follow_from_a' => 'Ваше питання буде пов\'язане з цією відповіддю:',
	'ask_follow_title' => 'Задати пов\'язане питання',
	'ask_limit' => 'Дуже часто задаєте питання - спробуйте ще раз пізніше',
	'ask_must_be_approved' => 'Щоб задавати питання необхідно підтвердження аккаунта. Перейти в ^1свій профіль^2.',
	'ask_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електронної пошти,^6, щоб задати питання.',
	'ask_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4 щоб задавати питання.',
	'ask_same_q' => 'Перш ніж продовжити, перевірте, чи не було таке питання вже задано:',
	'ask_title' => 'Задати питання',
	'c_notify_email' => 'Напишіть мені, якщо після мене буде додано коментар:',
	'c_notify_label' => 'Напишіть мені, якщо після мене додадуть коментар',
	'c_notify_x_label' => 'Напишіть мені (^), якщо після мене додадуть коментар',
	'c_waiting_your_approval' => 'Коментар очікує Вашого схвалення',
	'c_your_waiting_approval' => 'Ваш коментар скоро буде перевірений і схвалений.',
	'category_ask_not_allowed' => "У Вас немає прав задавати питання в цій категорії",
	'category_js_note' => 'Для вибору будь-якої категорії, будь ласка, увімкніть JavaScript в своєму браузері.',
	'category_required' => 'Будь ласка, оберіть категорію',
	'claim_button' => 'Я написав',
	'claim_a_popup' => "Прив\'язати відповідь до мого профіля",
	'claim_c_popup' => "Прив\'язати коментар до мого профіля",
	'claim_q_popup' => "Прив\'язати питання до мого профіля",
	'clear_flags_button' => 'прибрати відмітки',
	'clear_flags_popup' => 'Прибрати відмітки всіх користувачів',
	'close_button' => 'закрити',
	'close_duplicate_error' => 'Копія питання не знайдена - спробуйте ввести номер іншого питання, наприклад 123.',
	'close_duplicate' => 'Повна копія іншого питання',
	'close_form_button' => 'Закрити питання',
	'close_form_title' => 'Закриття питання',
	'close_original_note' => 'Ви також можете ввести URL питання у вигляді його номеру, наприклад 123.',
	'close_original_title' => 'URL оригінального питання:',
	'close_q_popup' => 'Закрити питання для нових відповідей',
	'close_reason_title' => 'Чому закрито питання:',
	'closed_as_duplicate' => 'закрито як копія:',
	'closed_with_note' => 'закрито з відміткою:',
	'comment_a_popup' => 'Додати коментар до цього питання',
	'comment_button' => 'коментувати',
	'comment_limit' => 'Дуже часто коментуєте - спробуйте ще раз пізніше',
	'comment_must_be_approved' => 'Для додавання коментаря необхідно підтвердження аккаунта. Перейти в ^1свій профіль^2.',
	'comment_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електронної пошти,^6, щоб додати коментар.',
	'comment_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4 щоб додати коментар.',
	'comment_on_a' => 'На відповідь: ',
	'comment_on_q' => 'На питання: ',
	'comment_q_popup' => 'Додати коментар до питання',
	'delete_a_popup' => 'Видалити відповідь назавжди',
	'delete_button' => 'видалити',
	'delete_c_popup' => 'Видалити коментар назавжди',
	'delete_q_popup' => 'Видалити питання назавжди',
	'duplicate_content' => 'Ваш аргумент схожий на копію іншого.',
	'edit_a_popup' => 'Редагувати відповідь',
	'edit_a_title' => 'Редагування відповіді',
	'edit_button' => 'редагувати',
	'edit_c_popup' => 'Редагувати коментар',
	'edit_c_title' => 'Редагування коментаря',
	'edit_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електронної пошти^6 щоб відредагувати це.',
	'edit_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4 щоб відредагувати це.',
	'edit_q_popup' => 'Відредагувати питання',
	'edit_q_title' => 'Редагування питання',
	'example_tags' => 'Приклади тегів: ',
	'flag_a_popup' => 'Відмітити як спам або флуд',
	'flag_button' => 'відмітити',
	'flag_c_popup' => 'Відмітити цей коментар як спам або флуд',
	'flag_hide_button' => 'відмітити і приховати',
	'flag_limit' => 'Дуже багато відміток - спробуйте ще раз пізніше',
	'flag_must_confirm' => 'Будь ласка, ^5підтвердіть адресу своєї електронної пошти,^6 щоб відмітити пост.',
	'flag_must_login' => 'Будь ласка, ^1увійдіть^2 або ^3зареєструйтесь^4 щоб відмітити пост.',
	'flag_not_allowed' => 'Відмітка не допустима',
	'flag_q_popup' => 'Відмітити це питання як спам або флуд',
	'follow_a_popup' => 'Задати пов\'язане питання до цієї відповіді',
	'follow_button' => 'задати пов\'язане питання',
	'follows_a' => 'Пов\'язане з відповіддю на:',
	'follows_q' => 'Про питання:',
	'hide_a_popup' => 'Приховати відповідь',
	'hide_button' => 'приховати',
	'hide_c_popup' => 'Приховати коментар',
	'hide_q_popup' => 'Приховати питання',
	'matching_tags' => 'Відповідні теги: ',
	'max_tags_x' => 'Доступно всього ^ тегів',
	'min_tags_x' => 'Будь ласка, додайте хоча б ^ тег/а/ів',
	'notify_email_note' => 'Конфіденційність: Ваша електронна адреса буде використовуватися тільки для відправки сповіщень.',
	'q_category_label' => 'Категорія:',
	'q_content_label' => 'Більше інформації про питання:',
	'q_hidden_author' => 'Питання було приховане автором',
	'q_hidden_flagged' => 'Питання було відмічено та приховано',
	'q_hidden_other' => 'Питання було приховане',
	'q_notify_email' => 'Надішліть мені лист, якщо на моє питання відповідають або коментують:',
	'q_notify_label' => 'Напишіть мені, якщо на моє питання відповідають або коментують',
	'q_notify_x_label' => 'Напишіть мені (^), якщо на моє питання відповідають або коментують',
	'q_tags_comma_label' => 'Теги - використовуйте кому як розділювач:',
	'q_tags_label' => 'Теги - використовувати дефіс для об\'єднання слів:',
	'q_title_label' => 'Питання в одному реченні:',
	'q_waiting_approval' => 'Питання очікує схвалення',
	'q_waiting_your_approval' => 'Питання очікує Вашого схвалення',
	'q_your_waiting_approval' => 'Ваше питання скоро буде перевірено та схвалено.',
	'recat_button' => 'змінити категорію',
	'recat_popup' => 'Змінити категорію питання/нь',
	'recat_q_title' => 'Зміна категорії питання',
	'reject_button' => 'відхилити',
	'reject_a_popup' => "Відхилити відповідь",
	'reject_c_popup' => "Відхилити коментар",
	'reject_q_popup' => "Відхилити питання",
	'remove_q_favorites' => 'Видалити питання з мого обраного',
	'reopen_button' => 'відкрити',
	'reopen_q_popup' => "Зерву відкрити питання",
	'reply_button' => 'відповісти',
	'reply_c_popup' => 'Відповісти на коментар',
	'reshow_button' => 'показати',
	'reshow_a_popup' => "Показати відповідь",
	'reshow_c_popup' => "Показати коментар",
	'reshow_q_popup' => "Показати питання",
	'retag_button' => 'змінити теги',
	'retag_cat_popup' => 'Змінити теги або категорію питання',
	'retag_popup' => 'Зміна тегів питання',
	'retag_q_title' => 'Зміна тегів питання',
	'save_silent_label' => "Збрегети та приховати відмітку про редагування",
	'select_popup' => 'Обрати цю відповідь найкращою',
	'select_text' => 'Найркаща відповідь',
	'show_1_comment' => 'Показати 1 коментар',
	'show_1_previous_comment' => 'Показати 1 попередній коментар',
	'show_x_comments' => 'Показати ^ коментарів',
	'show_x_previous_comments' => 'Показати ^ попередніх коментарів',
	'unflag_button' => 'заняти відмітку',
	'unflag_popup' => 'Зняти додану відмітку',
	'unselect_popup' => 'Натисніть, зоб прибрати виділене',
	'x_answers_title' => '^ Відповіді',
	'your_answer_title' => 'Ваша відповідь',
	'your_comment_a' => 'Ваш коментар до відповіді:',
	'your_comment_q' => 'Ваш коментар до питання:',
);
